services:
  - type: web
    name: backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    rootDir: frontend
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: https://backend-e9yy.onrender.com
        build: true